### ISSUE TITLE
Bypass blocking?

### ISSUE THREAD

**Issue by KonradIT** [eladnava/redalert-android#13]
How does the IDF know that the request is coming from the app? If it's through user agent it could be spoofed request-side.

**Comment by ofekashery** [comment]
Look at the Elad's response about this [here](https://github.com/eladnava/pikud-haoref-api/issues/3#issuecomment-452843933).

**Comment by eladnava** [comment]
Yup. Bypassing their restriction is illegal and will initiate a game of cat-and-mouse where they implement additional security checks, blocking the app from receiving alerts again in the future (affecting user trust) until we find a way to circumvent the latest security check, only for this process to go on forever.

The only proper solution is for Pikud Haoref to change their mind and allow access to our app once again.

**Comment by eladnava** [comment]
Pending Pikud Haoref's response (https://github.com/eladnava/redalert-android/issues/17#issuecomment-487422685)

**Comment by eladnava** [comment]
The app is up and running again! :)
