### ISSUE TITLE
Pikud haoref json url

### ISSUE THREAD

**Issue by itaiguli** [eladnava/redalert-android#14]
Where is the pikud haoref url json in the code?
from which the alerts arrive.

**Comment by ofekashery** [comment]
It's from @eladnava's API - [eladnava/pikud-haoref-api](https://github.com/eladnava/pikud-haoref-api)

**Comment by itaiguli** [comment]
How can I use it with the app?

**Comment by itaiguli** [comment]
How do the alerts come?

**Comment by ofekashery** [comment]
In fact, they are no longer. Pikud Haoref blocked the warnings file. The app and the API are no longer active. Read more [here](https://github.com/eladnava/pikud-haoref-api/issues/3#issuecomment-452843933).

**Comment by itaiguli** [comment]
I know, I search for new link

**Comment by eladnava** [comment]
@itaiguli The URL remains the same:
https://github.com/eladnava/pikud-haoref-api/blob/4ef2f861515c8b656f9d5e75309393835771a61e/config.js#L5

However, they have added some header checks to make sure that this URL is only fetched from within the Pikud Haoref website's JavaScript code. While it is easy to bypass, it would be illegal as they have implemented this check precisely to block this and other unofficial Tzeva Adom apps.

**Comment by eladnava** [comment]
The app is up and running again! 👍
