### ISSUE TITLE
פיקוד העורף מכתב לבעלי האפליקציה

### ISSUE THREAD

**Issue by DemonRem** [eladnava/redalert-android#17]
@eladnava אתמול קיבלתי מכתב בנוגע לבקשת גישה לAPI האומנם אבקש שתיצור עמי קשר במייל nemobam2@gmail.com אני העביר אלייך את הטפסים שנתנו לי pikud aaoref contact with me about the api access however please contact with me on mail nemobam2@gmail.com

**Comment by eladnava** [comment]
@DemonRem קיבלתי גם, אמלא את השאלון ואחזיר להם תשובה. 👍

**Comment by eladnava** [comment]
מילאתי את השאלון והחזרתי תשובה. נראה איך יגיבו.

**Comment by eladnava** [comment]
האפליקציה חזרה לפעילות! 👍
