### ISSUE TITLE
API Address Elad please read it

### ISSUE THREAD

**Issue by DemonRem** [eladnava/redalert-android#18]
Dear @eladnava now that there is high traffic rocket I using the api package in my host and its work great on my pc the net c# version I wonder where is that url located on the app? maybe its still can be arrvived or if you wish to use my address of the host is "185.241.7.187"

**Comment by eladnava** [comment]
@DemonRem As per https://github.com/eladnava/redalert-android/issues/17#issuecomment-487422685 we are awaiting Pikud Haoref's response to bring back the app. 

Creating an alternative alerts API for the app won't help as anyway we need to get official approval to continue operations.

I appreciate your work and intention. 👍

**Comment by eladnava** [comment]
The app is up and running again! 👍
