### ISSUE TITLE
היי, איך היסטוריית התרעות עובדת?

### ISSUE THREAD

**Issue by eladofer** [eladnava/redalert-android#19]
כותרת

**Comment by eladnava** [comment]
Hi @eladofer,
There is a backend API (redalert.me/alerts) which returns a JSON array of historical alerts which are stored in the RedAlert backend database.

**Comment by eladofer** [comment]
איך זה מתבטא באפליקציה?
הכוונה שלי איפה באפליקציה נעשה הפעולה הזאת?

**Comment by eladnava** [comment]
@eladofer It happens in `MainActivity.getRecentAlerts()`:
https://github.com/eladnava/redalert-android/blob/c96c91225b251cf4684655550df47a41e1a565fe/app/src/main/java/com/red/alert/activities/Main.java#L390
