### ISSUE TITLE
Android Background Alert not working

### ISSUE THREAD

**Issue by DemonRem** [eladnava/redalert-android#20]
Dear @eladnava

for the last few days while there is alert in Israel , I choose all area , from some reason its not giving alert, as I open the app after I heard there is a rocket , its been write in the app where but not notify me alerts & sounds

**Comment by eladnava** [comment]
Hi @DemonRem,
This is quite strange, let's investigate.


If you could please provide the following information about the device experiencing this issue, that would be great:

1) Device manufacturer
2) Device model name
3) Android OS version

**Comment by DemonRem** [comment]
@eladnava
1. Haweii
2. P30 ( ELE-L29)
3. OS Version is 9

**Comment by DemonRem** [comment]
I done all of that , how I can check if that was the issue ?

**Comment by DemonRem** [comment]
@eladnava , 

today was alert at hotef aza , and still the application didn't send notify and not a sound

**Comment by eladnava** [comment]
This is quite strange, I will investigate further and let you know (waiting for the next alert unfortunately).

**Comment by DemonRem** [comment]
@eladnava , there were a like few alert , did you manage to check that out?

**Comment by eladnava** [comment]
Hi @DemonRem,
Yes, I was able to receive these alerts on my phone successfully with the app in the background (after whitelisting the app from App Battery Optimizations).

Are you still not receiving any alerts after whitelisting?

**Comment by DemonRem** [comment]
no

**Comment by eladnava** [comment]
Hi @DemonRem,
Let's check whether the app is currently running in your phone, and checking its logs, by following these instructions.

1. Please install `adb` by following the instructions in this guide:
http://lifehacker.com/the-easiest-way-to-install-androids-adb-and-fastboot-to-1586992378

2. Enable "Developer Options" in the device settings:
http://www.greenbot.com/article/2457986/how-to-enable-developer-options-on-your-android-phone-or-tablet.html

3. Connect the device to your computer via a USB cable

4. If the "Trust this computer" dialog appears on the device, press "Yes"

5. Open a terminal prompt on your computer

Run the following command:

```
adb shell 'logcat -d --pid=$(pidof -s com.red.alert)' > logcat.txt
```

7. Attach `logcat.txt` to this e-mail

**Comment by DemonRem** [comment]
this is what I ge/system/bin/sh: logcat -d --pid=$(pidof -s com.red.alert): not found

right now I on the app I see It on my eyes but seems there is no log

**Comment by eladnava** [comment]
Hi @DemonRem,
Let's please try another command:

```
adb logcat -d | grep $(echo $(adb shell pidof -s com.red.alert)) > logcat.txt
```

Please check whether `logcat.txt` is generated well this time.

**Comment by DemonRem** [comment]
i am using windows from some reason i have that error 
'grep' is not recognized as an internal or external command,
operable program or batch file.

**Comment by eladnava** [comment]
Hi @DemonRem,
Thanks for your help, let's try this instead:

```
adb logcat -d *:S Pushy > logcat.txt
```

**Comment by DemonRem** [comment]
[logcat.txt](https://github.com/eladnava/redalert-android/files/3590846/logcat.txt)

I don't see anything in that log

**Comment by DemonRem** [comment]
@eladnava , there is was alert now once I was at the application the alert activated , but when I didn't its didn't was activated

**Comment by eladnava** [comment]
Hi @DemonRem,
I was able to receive the alerts yesterday as push notifications immediately as they were broadcasted.

It definitely seems that your Huawei device is killing the RedAlert app while it is in the background.

I just read on [this page](https://dontkillmyapp.com/huawei) that Huawei devices running EMUI 9.0 and up come with another Power Saving Mechanism called **PowerGenie** which kills all apps running in the background for more than 60 minutes.

Please run the following command on your computer (after connecting your device) to completely delete and disable PowerGenie:
```
adb shell pm uninstall --user 0 com.huawei.powergenie
```

Please let me know if this command succeeds, and then we'll be able to see whether the issue is resolved next time there is a red alert.

**Comment by eladnava** [comment]
Hi @DemonRem,
Did the command work? Was PowerGenie responsible for the issue you faced?

Please clarify what you mean by adding an alert? A sound? What exactly?

**Comment by DemonRem** [comment]
@eladnava I didn't disable the powergeniue i did something else i don't remember what but i will update you
anyway i mean i want to add new sound alert

**Comment by eladnava** [comment]
Hi @DemonRem,
Which sound are you looking to add? As mentioned in https://github.com/eladnava/redalert-android/issues/21#issuecomment-526804549, there is already a similar sound existing in the app.
