### ISSUE TITLE
Tel Aviv Red Alert Sound For the app

### ISSUE THREAD

**Issue by DemonRem** [eladnava/redalert-android#21]
Link For the Alert : https://f2h.io/zdx23wupuqul

I also try to add the sound in the source , and when install the app , its say not application not installed , 
moreover its create a debug file on output , its ok?

**Comment by DemonRem** [comment]
@eladnava 

after I add the sound to the res/raw folder mp3 , I compiled the app
I see the string I add but the sound not play, I think I doing smth wrong, can you tell me what I doing wrong I cant add my sound

**Comment by eladnava** [comment]
Hi @DemonRem,
Unfortunately we can't use this recording as it contains a lot of background noise. 

Also, please listen to `Siren 5` which is already available in the app's sound selection menu, which sounds like the Tel Aviv sound you uploaded, without the background noise.
