### ISSUE TITLE
האפליקציה לא נרשמת לשרתי צבע אדום 

### ISSUE THREAD

**Issue by DemonRem** [eladnava/redalert-android#22]
האפליקציה ממשיכה להודיע נרשם לשירותי צבע אדום

ארעה שגיאה בהרשמה לשירותי עדכוני דחיפה של האפליקציה , ננסה לרשום אותך שוב מאוחר יותר

org.apache.http.conn.httphostconnectexceptionL connection to https://redalert.me refused

Now i have this error 
![Screenshot_20191112_123204_com red alert](https://user-images.githubusercontent.com/29927382/68664183-968f9d80-0548-11ea-9034-a42975201c91.jpg)

**Comment by eladnava** [comment]
@DemonRem תודה על הדיווח

השרתים נפלו עקב עומס לא צפוי, הקצאתי עוד משאבים והכל חזר לפעול כעת. 👍
