### ISSUE TITLE
Restore the Sound Extrenal Selector Issue

### ISSUE THREAD

**Issue by DemonRem** [eladnava/redalert-android#23]
I restore the sound extrenal to set my music because the alert giving me crazy , so I did restore that function I using mp3 as my music format , but once I did self test on the app he not playing the music , from some reason I check all my phone music and I get the same issue , but once I check the redalert app sound , on the self test he playing them, so what wrong?
[app-debug.zip](https://github.com/eladnava/redalert-android/files/3871207/app-debug.zip)

After editing.

**Comment by eladnava** [comment]
Hi @DemonRem,
Sorry but I have decided to remove the Alert External Sound selection as it was causing weird issues with sound not playing on some phones, as you are witnessing.

You are welcome to debug it further by looking at the logcat but I cannot help you further in this regard as this feature is no longer supported.
