### ISSUE TITLE
האם אתה יש בכוונתך לשדרג ?

### ISSUE THREAD

**Issue by yakirdayan** [eladnava/redalert-android#24]
האם יש בכוונתך לשדרג את האפליקציה ל sdk28 
כפי שגוגל החלה לדרוש מכל מפתחי האפליקציות? 

שאלה נוספת, אני רואה באפליקציה את ההיסטוריית התראות ומשום מה זה לא מציג את ההתראות האחרונות, זה מפספס את ה 10 האחרונות שהיו.
תודה

**Comment by eladnava** [comment]
היי יקיר,
השדרוג יבוצע כאשר גרסה נוספת תשוחרר לפליי סטור. כל עוד אין מה לעדכן באפליקציה עצמה, לא רואה סיבה לעדכן רק בשביל להגדיר `targetSdkVersion 28`.

הייתה תקלה בשרתי האפליקציה (דטבייס) ביממה האחרונה שגרמה לפספוס התרעות לצערי. התקלה טופלה ולא אמורה לחזור על עצמה לעולם. 👍
