### ISSUE TITLE
בעיה בשרת הראשי

### ISSUE THREAD

**Issue by DemonRem** [eladnava/redalert-android#25]
@eladnava 

בוקר טוב אלעד תקשיב לאפליקציה יש תקלה כפי הנראה , היא לא מצליחה להתחבר לשרת הראשי
אלא רק למשני ופרק זמן התגובה שלה במסך עצמו ממש ענקי , וההתראות באות באיחור של 3 שניות פעם כאן ופעם מדויק

**Comment by eladnava** [comment]
@DemonRem בוקר טוב,
תודה רבה על הדיווח. עשית סקייל אפ לשרתים ואני מאמין שזה יעבוד פיקס מעכשיו.

בבקשה עדכן אם אתה חווה שוב בעיה בעתיד.

**Comment by DemonRem** [comment]
סקייל פול אין לנח מושג מזה.
