### ISSUE TITLE
Alert Sound even when set to silent

### ISSUE THREAD

**Issue by mbrevda** [eladnava/redalert-android#26]
Even when the alert sound is set to No Sound an alert is still heard. The desired behavior would be to respect the "No Sound" setting.
Thanks!

**Comment by eladnava** [comment]
Hi @mbrevda,
Have you enabled Secondary Notifications (התרעות משנה)? It's possible the sound there is heard because the alert matched one of your selected cities or regions in Secondary Notifications but not primary, or vice versa.

**Comment by mbrevda** [comment]
Actually, its the seconds alerts that the the issue. They are enabled and set to silent, but are still playing an alert.

![Screenshot_20210513-174533.png](https://user-images.githubusercontent.com/293004/118142715-4e8a5900-b413-11eb-9019-acbbc5cedae4.png)

**Comment by eladnava** [comment]
Hi @mbrevda,
Thanks for your report, this has now been fixed in 12bf445 and will be released to the Google Play Store in the next few days in version `1.0.12`. 👍

**Comment by mbrevda** [comment]
Thanks! Looking forward to testing

**Comment by mbrevda** [comment]
Seems fixed, thanks!

**Comment by eladnava** [comment]
Glad to hear, @mbrevda! 😄
