### ISSUE TITLE
Way to change used map in app

### ISSUE THREAD

**Issue by Wicoler** [eladnava/redalert-android#27]
Hi i like your application and my request is that you will make an option to change in what map type it will open
I dont really like that it auto opens in google maps for some reasons and would like that you make an option to change where it opens (more privecy orianted map)
Like open street maps
Thank you!

**Comment by eladnava** [comment]
Hi @Wicoler,
Thanks for your suggestion. There's no private information being provided to Google Maps, except for the geo-coordinates of the alert territory you clicked.

Google Map works great. I don't see a reason to change it and no private information is being leaked or passed on to Google.

**Comment by Wicoler** [comment]
Ok nice to know thank you dev!
Keep up the good work!
