### ISSUE TITLE
Where is source code for iOS app?

### ISSUE THREAD

**Issue by emanuelb** [eladnava/redalert-android#28]
Searched for source-code of ios app:
https://apps.apple.com/il/app/zb-dwm-htr-wt-bzmn-mt/id937914925
in user: https://github.com/eladnava
and didn't found any results, please publish the source-code for the iOS app as well.

**Comment by eladnava** [comment]
Thanks for asking @emanuelb, the iOS app is now published at [eladnava/redalert-ios](https://github.com/eladnava/redalert-ios).
