### ISSUE TITLE
Git tag releases & Use github releases and add universal .apk file to them

### ISSUE THREAD

**Issue by emanuelb** [eladnava/redalert-android#29]
This repo has no tags, please tag the latest releases:
https://github.com/eladnava/redalert-android/tags

And add universal .apk file (Android app) in github releases: (add the .apk file as asset)
https://github.com/eladnava/redalert-android/releases

**Comment by eladnava** [comment]
Hi @emanuelb,
Thanks for your suggestion. At this time, distribution of the app is limited to the Google Play Store only.

**Comment by eladnava** [comment]
This has now been completed, and a download link of the latest APK build has been added to the README.
