### ISSUE TITLE
Add Github topics to repo

### ISSUE THREAD

**Issue by emanuelb** [eladnava/redalert-android#30]
Improve project discoverability by adding github topics, see:
https://help.github.com/en/github/administering-a-repository/classifying-your-repository-with-topics

Related topics are:
https://github.com/topics/israel
https://github.com/topics/irondome
https://github.com/topics/idf
https://github.com/topics/emergency
https://github.com/topics/tseva-adom
https://github.com/topics/siren
https://github.com/topics/oref
https://github.com/topics/missile
https://github.com/topics/missile-alert
https://github.com/topics/red-alarm
https://github.com/topics/red-alert
https://github.com/topics/redalert

**Comment by eladnava** [comment]
Hi @emanuelb,
Thanks for your suggestion. I've added some of your recommended topics to the GitHub project.
