### ISSUE TITLE
Upgrade targetSdkVersion & compileSdkVersion to 30 (target Android 11) 

### ISSUE THREAD

**Issue by emanuelb** [eladnava/redalert-android#32]
Currently the app target SDK 29 (Android 10) which is the minimum required for publishing the apk to google-play now (in November will be required to upgrade to SDK 30), it's better to upgrade sooner to benefit from the security improvements.

list of changes for apps that target Android 11: (see that it's not affecting the app, fix issues if exists, etc..)
https://developer.android.com/about/versions/11/behavior-changes-11

Here values should be changed to 30:
https://github.com/eladnava/redalert-android/blob/e7653e244e12b2f0747f3c3d93c93d2214e36013/app/build.gradle#L5
https://github.com/eladnava/redalert-android/blob/e7653e244e12b2f0747f3c3d93c93d2214e36013/app/build.gradle#L10
```
compileSdkVersion 30
targetSdkVersion 30
```

**Comment by eladnava** [comment]
Hi @emanuelb,
Thanks for your suggestion. Please submit a PR with the requested changes, after testing throughly that the project complies successfully and the app works properly with the aforementioned changes. 👍
