### ISSUE TITLE
Upgrade Deps in build.gradle

### ISSUE THREAD

**Issue by emanuelb** [eladnava/redalert-android#33]
https://github.com/eladnava/redalert-android/blob/b03c9c8d38824aed71cca4cc6f45fa784a6bf903/build.gradle#L13
latest version for `com.google.gms:google-service` is: 4.3.5

https://github.com/eladnava/redalert-android/blob/a2ab5f9fdb982f02457fca05cadd32c0ab1b02fc/app/build.gradle#L29
latest version for `com.google.firebase:firebase-messaging` is: 21.1.0

https://github.com/eladnava/redalert-android/blob/a2ab5f9fdb982f02457fca05cadd32c0ab1b02fc/app/build.gradle#L32
latest version for `com.google.android.gms:play-services-location` is: 18.0.0

**Comment by eladnava** [comment]
Hi @emanuelb,
Thanks for your suggestion. Please submit a PR with the requested changes, after testing throughly that the project complies successfully and the app works properly with the aforementioned changes. 👍
