### ISSUE TITLE
Remove/Migrate from JCenter

### ISSUE THREAD

**Issue by emanuelb** [eladnava/redalert-android#34]
https://github.com/eladnava/redalert-android/blob/167c01f874870c88faad618ee56fde6abbdb41bc/.idea/jarRepositories.xml#L14-L18

https://github.com/eladnava/redalert-android/blob/167c01f874870c88faad618ee56fde6abbdb41bc/build.gradle#L5
https://github.com/eladnava/redalert-android/blob/167c01f874870c88faad618ee56fde6abbdb41bc/build.gradle#L22

Jcenter service is closed (currently in read-only mode, no updates for packages will be made)
more details on needed migration:
https://developer.android.com/studio/build/jcenter-migration

and here content on how to migrate:
https://jeroenmols.com/blog/2021/02/04/migratingjcenter/

**Comment by eladnava** [comment]
Hi @emanuelb,
Thanks for your suggestion. Please submit a PR with the requested changes. 👍
