### ISSUE TITLE
Remove android.enableJetifier line from build.gradle

### ISSUE THREAD

**Issue by emanuelb** [eladnava/redalert-android#35]
https://github.com/eladnava/redalert-android/blob/b03c9c8d38824aed71cca4cc6f45fa784a6bf903/gradle.properties#L19

See this guide for the steps to ensure it's safe to remove above line (check that all deps are already fully migrated to AndroidX)
https://medium.com/dipien/say-bye-bye-to-android-jetifier-a7e0d388f5d6

**Comment by eladnava** [comment]
Hi @emanuelb,
Thanks for your suggestion. Please submit a PR with the requested changes, after testing throughly that the project complies successfully with the aforementioned change. 👍
