### ISSUE TITLE
Use geofencing instead of polling?

### ISSUE THREAD

**Issue by mbrevda** [eladnava/redalert-android#36]
Would it make sense to use geofencing instead of poling for location? In theory, this should reduce battery usage while increasing accuracy

**Comment by eladnava** [comment]
Hi @mbrevda,
Thanks for the suggestion! While that would indeed be an excellent alternative more favorable than location polling, Android currently limits the number of geofences per app to 100:

> You can have multiple active geofences, with a limit of 100 per app, per device user.

More info: https://developer.android.com/training/location/geofencing

Location alerts currently work nation-wide without you having to select a certain area, which is handy if you are driving between cities over long distances.

Thanks again for your suggestion!
