### ISSUE TITLE
orot location is wrong

### ISSUE THREAD

**Issue by yotamleo** [eladnava/redalert-android#37]
orot coordinates are pointing to orot collage and not moshav orot 
so the location based alerts for rehovot and area are a bit off..

fix is:
  {
    "name": "אורות",
    "name_en": "Orot",
    "zone": "לכיש",
    "zone_en": "Lakhish",
    "time": "45 שניות",
    "time_en": "45 seconds",
    "countdown": 45,
    "lat": 31.741667,
    "lng": 34.734444,
    "value": "אורות"
  },

**Comment by eladnava** [comment]
Fixed via #38.
