### ISSUE TITLE
Publish server and website source-code

### ISSUE THREAD

**Issue by emanuelb** [eladnava/redalert-android#39]
Publish the server and website https://www.redalert.me/ source-code, searched for it in user: https://github.com/eladnava
and didn't found any results, please publish the source-code for the server-side+website side as well.

**Comment by eladnava** [comment]
Hi @emanuelb,
At this time, for security-by-obscurity purposes, the source code of the backend and website will not be published, to prevent potential attackers from studying the source code and finding potential vulnerabilities.
