### ISSUE TITLE
Cities that get alert for but not on a list 

### ISSUE THREAD

**Issue by FelixKras** [eladnava/redalert-android#42]
אשקלון - דרום' & ' אשקלון - צפון' (notice the Hebrew) 
Receives an alert (true alerts from 18.06.22 and also 16.07.22) but you cannot add it to the list of cities you get an alert for. 

![Screenshot_20220618-084600](https://user-images.githubusercontent.com/42567361/179348413-e50b8a7b-e8c3-4766-b257-e14cbbc74cd6.png)
![Screenshot_20220618-084530](https://user-images.githubusercontent.com/42567361/179348415-512647c5-86ae-445b-ae30-09bed74e3f06.png)
![Screenshot_20220716-120641](https://user-images.githubusercontent.com/42567361/179348465-68068972-79bc-4009-817a-959af1b672dc.png)

**Comment by eladnava** [comment]
Hi @FelixKras,
Thanks so much for creating this issue. 

The Home Front Command has recently updated the city names, and I've gone forth and [re-scraped them](https://github.com/eladnava/pikud-haoref-api/commit/bdd4263f088fea7dafa80c29ac8424ae87f490e1) and updated the `cities.json` accordingly in https://github.com/eladnava/redalert-android/commit/cc214b391cfa365603653e2443bca81236e24dd1.

A new version of the app will be released to Google Play soon.
