### ISSUE TITLE
Please add an auto-refresh feature 

### ISSUE THREAD

**Issue by eitan07** [eladnava/redalert-android#43]
Besides of that the app is great

**Comment by eladnava** [comment]
Hi @eitan07,
Thanks so much for the recommendation! 

The app already has auto-refresh built in, every [10 seconds](https://github.com/eladnava/redalert-android/blob/167c01f874870c88faad618ee56fde6abbdb41bc/app/src/main/java/com/red/alert/config/RecentAlerts.java#L5).

If you observe the app's action bar, you'll see the loading icon appear briefly every 10 seconds indicating the list of recent alerts is being refreshed.
