### ISSUE TITLE
Notification filtering

### ISSUE THREAD

**Issue by yakirdayan** [eladnava/redalert-android#44]
How do you prevent an alert that works in city X from appearing to the person who chose to see city Y?

**Comment by eladnava** [comment]
Hi @yakirdayan,
Are you referring to the "Recent Alerts" screen (the main activity)? That list shows any and all recently issued rocket alerts by the Home Front Command, regardless of the user's city/region selection. 

The city/region selection only controls what alerts will be sent as push notifications to that user when an alert in the selected region/city is published by the Home Front Command.
