### ISSUE TITLE
Feature Red Alert Reason

### ISSUE THREAD

**Issue by LievreAI** [eladnava/redalert-android#45]
באתר של פיקוד העורף למשל רשום סיבה על מה צבע אדום 
אני מבין שיש כמה סיבות (חדירת מחבלים , אזעקות צבע אדום ...)
אפשר להוסיף לאפליקציה שתשדר מה הסיבה לצבע אדום 
האפליקציה פשוט מראה את ההתראות יהיה נפלא גם עם יהיה אופציה לראות מה הסיבה
הרבה אפליקציות אחרות עושות את זה וזה באמת יהיה נפלא לראות דבר כזה פה
![Screenshot 2023-07-15 112926](https://github.com/eladnava/redalert-android/assets/84988313/4963f435-258e-4a7a-8719-9b5298d7deb1)

**Comment by eladnava** [comment]
@LievreAI תודה על ההצעה, זה בפיתוח. אוסיף כשאמצא זמן 👍

**Comment by eladnava** [comment]
תודה על ההמתנה, נוסף בגרסה `1.0.17` שעלתה למרקט ותאושר על ידי גוגל פליי בימים הקרובים. 🎉
