### ISSUE TITLE
Github releases are outdated (APKs are old, git tags are missing)

### ISSUE THREAD

**Issue by paulfertser** [eladnava/redalert-android#47]
Hello,
Both 5015e93bacc6f3860c1729a60952535defc0ae06 (1.0.26) and fd3d80f2358a9a9044c5a90c18561a3e01ef4c07 (1.0.27) are missing regular git tags, same about all the previous versions, the last tag is 1.0.15 from Aug 8 2022.
No released binaries were officially published since 1.0.15 either.
Please add the latest releases and some machinery to ensure github releases are updated.
Thank you very much for working on this literally life-saving app, and best wishes to you, all of your family and friends and everybody else working so hard on the safety of everybody affected.

**Comment by eladnava** [comment]
Hi @paulfertser,
Thanks for your kind words!

Releases have been tagged and the latest APK has been uploaded.
