### ISSUE TITLE
"Confrontation Line" event presentation is confusing

### ISSUE THREAD

**Issue by paulfertser** [eladnava/redalert-android#48]
Attached is a screenshot showing two different types of events for comparison.
The "Confrontation Line" event lacks indication of the larger region it's related to. Also it has a "Rocket fire" note which is likely misleading in this case (as it requires a different set of protection features).
![IMG_20231017_201536](https://github.com/eladnava/redalert-android/assets/122414/e0b7f1a0-600d-4f89-896d-92efad4c23e3)
(nitpicking: it looks like "Rocket fire" is used for any kind of areal threat, be it shells, drones, rockets or anything else I'd prefer not to imagine)

**Comment by eladnava** [comment]
Hi @paulfertser,
"Confrontation Line" is an [official region name](https://www.oref.org.il/Shared/Ajax/GetCitiesMix.aspx?lang=en) decided by Pikud Haoref (Home Front Command) for the region in the North of Israel along the Lebanese border. It is translated from the official region name in Hebrew "קו העימות" ([wiki](https://he.wikipedia.org/wiki/%D7%A7%D7%95_%D7%94%D7%A2%D7%99%D7%9E%D7%95%D7%AA)).

"Rocket fire" is the type of threat issued by Pikud Haoref - it is not a generic text that always appears - there are about 15 different threat types:
https://github.com/eladnava/redalert-android/blob/795cd9f5635d37d4ff88ffcbcf7f3dd9e533cd08/app/src/main/java/com/red/alert/utils/metadata/LocationData.java#L319-L376

As you can see there are different threat types which are displayed according to the alert Pikud Haoref issues out.

Hopefully that clears things up.
