### ISSUE TITLE
If I download from GIT 

### ISSUE THREAD

**Issue by zsergei2000** [eladnava/redalert-android#50]
If I download from GIT and install it on the emulator. I should be able to register with Fireb. Writes an error. Or a working application only with GOOGLE MARKET?

**Comment by eladnava** [comment]
Hi @zsergei2000,
Please make sure you are using a "Google APIs" emulator system image, and that you have logged into the Google Play app on the emulator with a valid Google account. 

This is required for Firebase Cloud Messaging push registration.
