### ISSUE TITLE
Add Portuguese Translation to Alerts

### ISSUE THREAD

**Issue by rodsasilva** [eladnava/redalert-android#58]
Hello there!

I'd be happy to volunteer my time to help translate documentation and alerts into Portuguese. There are Brazilians and Portuguese residents living in Israel, and families in Portuguese-speaking countries who are following the situation regarding the attacks. I think it's important, so I'm leaving my contact information below:

Email: rodrigo.sabinoti@gmail.com
LinkedIn: https://www.linkedin.com/in/rodsasilva/
X (formerly Twitter): https://x.com/seibim

**Comment by eladnava** [comment]
Hi @rodsasilva,
Thanks so much for offering to help translate the app to Portuguese! 👍 

To translate, please download this [strings.xml](https://github.com/eladnava/redalert-android/raw/master/app/src/main/res/values-en/strings.xml) file and open it in a text editor of your choice. The, translate each word or phrase inside the `<string>...</string>` elements. Please do not translate the value inside the `name=""` property.

Once it's done, you can attach the file in a response to this issue.

Thanks again!

**Comment by rodsasilva** [comment]
Hi @eladnava ,

I would like to express my sincere gratitude for the opportunity to contribute to the project.
Attached is the file translated into Portuguese.
When you put it into production, please let me know so that I can update the application and validate the Portuguese version.
I am available to continue contributing with my skills whenever there is an opportunity.

Thank you again for the opportunity.
[strings.zip](https://github.com/user-attachments/files/16828943/strings.zip)

Best regards,
Rodrigo Sabino da Silva

**Comment by eladnava** [comment]
Hi @rodsasilva,
Well done! Thanks so much! 💯 

Your translation has been added to the app in commit https://github.com/eladnava/redalert-android/commit/e389606f9eaaa1246b8be680411c86dffc0d60c7 and published to Google Play in version `1.0.52`. It will take a few hours for the update to become available.

Really appreciate your help with this!
