### ISSUE TITLE
Cartoon voice during alert

### ISSUE THREAD

**Issue by Zarkorix** [eladnava/redalert-android#59]
RedAlert 1.0.67

Problem description:

All alert sounds now also come with a cartoonish voice saying "incoming!" along with a distorted rocket sound. Was this an intentional change? It occurs even when "no sound" is selected. Or alternatively this is some bizarre change in Android 15 which I recently upgraded to...

**Comment by Zarkorix** [comment]
An example using the self-test function.

https://github.com/user-attachments/assets/84212bd2-14f9-40e6-98d7-cee22d551b17

**Comment by eladnava** [comment]
Hi @Zarkorix,
This was not an intentional change, it was a bug introduced in the latest version when the sound resource IDs changed.

Until Google approves a new update, please uninstall and reinstall the app from Google Play, and the issue will be resolved.

**Comment by Zarkorix** [comment]
Excellent, that worked - thanks @eladnava.
