### ISSUE TITLE
Issue with Earthquake Alert Detection

### ISSUE THREAD

**Issue by liraz747** [eladnava/redalert-android#61]
A couple of weeks ago, there was a false earthquake alert (due to bombings) that showed up on the official Home Front Command app and the Tzofar app, but not on this one.  This makes me think there might be a problem with how this app detects these kinds of alerts.

I sent you an email about this earlier too, and thanks for looking into it!  I saw your reply where you mentioned the alert wasn't on the Home Front Command website (`www.oref.org.il`) and that you contacted the Tzofar developers to see how they got it.

Since Tzofar *did* get the alert, maybe they're using a different data source or a different way of grabbing the alerts?

Any news on the investigation or anything you heard back from the Tzofar team would be awesome!  Yeah, earthquakes are extremely rare and unlikely in here, but it would give me peace of mind knowing that these alerts would work properly 😅

Thanks again!

**Comment by eladnava** [comment]
Hi @liraz747,
Thanks so much for creating this issue.

Unfortunately, I've contacted the Tzofar team multiple times about this, and they have declined to disclose how their app was able to send out this alert even though it was not made available through the "official" HFC API.

Most likely, they have an alternative data source for the alerts, but are not interested in disclosing or sharing it for whatever reason.

In any case, the HFC admitted that there was a bug which they have now fixed which prevented the distribution of this alert, so hopefully in the future, earthquake alerts will be distributed properly by the app.

**Comment by liraz747** [comment]
That's unfortunate that the Tzofar developers weren't able to share their method, but I'm very glad to hear the HFC has identified and fixed the bug. It's really reassuring to know this has been addressed. Thanks so much for the update and for your efforts on this!
